#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - gnupg2
  - unzip
  - ca-certificates
  - curl 
  - apt-transport-https 
  - lsb-release
  - gnupg
groups:
  - vault
users:
  - default
  - name: vault
    gecos: Vault Agent
    primary_group: vault
    ssh_authorized_keys:
      - ${ssh_key}
write_files:
  - path: /opt/vault/run.sh
    content: |
      #! /bin/bash

      export IP_ADDRESS=$(hostname -I)
      export VAULT_API_ADDR="https://$IP_ADDRESS:8200"

      vault server -config=/opt/vault/config/server.hcl
    permissions: '0700'
  - path: /opt/vault/config/server.hcl
    content: |
      seal "azurekeyvault" {
        tenant_id = ${tenant_id}
        vault_name = ${vault_name}
        key_name =  ${key_name}
      }

      storage "postgresql" {
        connection_url = "postgres://${postgres_admin_username}:${postgres_admin_password}@${postgres_host}:5432/vault?sslmode=verify-full"
      }
      
      listener "tcp" {
        "address" = "0.0.0.0:8200",
        "tls_disable" = true
      }
    permissions: '0600'
  - path: /tmp/vault.sql
    content: |
      CREATE TABLE vault_kv_store (
        parent_path TEXT COLLATE "C" NOT NULL,
        path        TEXT COLLATE "C",
        key         TEXT COLLATE "C",
        value       BYTEA,
        CONSTRAINT pkey PRIMARY KEY (path, key)
      );

      CREATE INDEX parent_path_idx ON vault_kv_store (parent_path);

      CREATE TABLE vault_ha_locks (
        ha_key                                      TEXT COLLATE "C" NOT NULL,
        ha_identity                                 TEXT COLLATE "C" NOT NULL,
        ha_value                                    TEXT COLLATE "C",
        valid_until                                 TIMESTAMP WITH TIME ZONE NOT NULL,
        CONSTRAINT ha_key PRIMARY KEY (ha_key)
      );
runcmd:
  - wget 
  - chmod +x /opt/vault/run.sh
  - chown -R vault:vault /opt/vault
  - wget -O /tmp/vault.zip https://releases.hashicorp.com/vault/1.8.4/vault_1.8.4_linux_amd64.zip
  - unzip /tmp/vault.zip -d /usr/local/bin/
  # install posgresql 11 client
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - apt-get update
  - apt-get install -y postgresql-client-11