#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - gnupg2
  - unzip
  - ca-certificates
  - curl 
  - apt-transport-https 
  - lsb-release
  - gnupg
groups:
  - vault
users:
  - default
  - name: vault
    gecos: Vault Agent
    primary_group: vault
    ssh_authorized_keys:
      - ${ssh_key}
write_files:
  - path: /etc/systemd/system/vault.service
    encoding: b64
    content: ${systemd}
    permissions: '0644'

  - path: /opt/vault/run.sh
    content: ${run_script}
    permissions: '0700'
  - path: /opt/vault/config/server.hcl
    content: |
      seal "azurekeyvault" {
        tenant_id = "${tenant_id}"
        vault_name = "${vault_name}"
        key_name =  "${key_name}"
      }

      storage "postgresql" {
        connection_url = "postgresql://${postgres_host}:5432/vault?user=${postgres_admin_username}&password=${postgres_admin_password}&sslmode=require"
        ha_enabled = "true"
      }
      
      ui = true

      listener "tcp" {
        "address" = "0.0.0.0:8200",
        "tls_disable" = true
      }
    permissions: '0600'
  - path: /tmp/vault.sql
    encoding: b64
    content: ${psql_query}
runcmd:
  - wget 
  - chmod +x /opt/vault/run.sh
  - chown -R vault:vault /opt/vault
  - wget -O /tmp/vault.zip https://releases.hashicorp.com/vault/1.8.4/vault_1.8.4_linux_amd64.zip
  - unzip /tmp/vault.zip -d /usr/local/bin/
  # install posgresql 11 client
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - apt-get update
  - apt-get install -y postgresql-client-11
  - export PGPASSWORD="${postgres_admin_password}"; psql -h ${postgres_host} -p 5432 -d vault -U ${postgres_admin_username} -f /tmp/vault.sql
  - systemctl enable vault.service
  - systemctl start vault.service
  - echo 'export VAULT_ADDR="http://127.0.0.1:8200"' >> /home/vault/.bashrc