#cloud-config
package_upgrade: true
packages:
  - xfce4
  - xfce4-session
  - xrdp
  - python3-pip
  - flameshot 
  - i3-wm 
  - rofi 
  - i3status 
  - suckless-tools 
  - clipit
  - firefox
snap:
  commands:
    - 'snap install --classic kubectl'
    - 'snap install --classic helm'
    - 'snap install jq'
    - 'snap install --classic certbot'
users:
  - default
write_files:
  - path: /etc/skel/.xsession
    content: |
      xfce4-session
    permissions: '0640'
runcmd:
  # change default SSH port
  - 'echo "Port 2022" >> /etc/ssh/sshd_config.d/50-cloudimg-settings.conf'
  - 'systemctl restart sshd'
  # Setup Certbot for SSL Certs
  - 'ln -s /snap/bin/certbot /usr/bin/certbot'
  - 'certbot certonly --standalone --no-eff-email --email ${admin_email} --agree-tos --preferred-challenges http -d ${url}'
  # change xrdp default certs to letsencrypt certs
  - 'rm /etc/xrdp/key.pem'
  - 'ln -s /etc/letsencrypt/live/${url}/privkey.pem /etc/xrdp/key.pem'
  - 'rm /etc/xrdp/cert.pem'
  - 'ln -s /etc/letsencrypt/live/${url}/fullchain.pem /etc/xrdp/cert.pem'
  # change default RDP port
  - "sed -i 's/port=3389/port=2023/' /etc/xrdp/xrdp.ini"
  - 'systemctl enable xrdp'
  - 'systemctl restart xrdp'
  