#cloud-config
package_upgrade: true
packages:
  - xfce4
  - xfce4-session
  - xrdp
  - python3-pip
  - flameshot 
  - i3-wm 
  - rofi 
  - i3status 
  - suckless-tools 
  - apt-transport-https
  - firefox
  - gnupg2
  - unzip
  - ca-certificates
  - curl 
  - apt-transport-https 
  - lsb-release
  - gnupg
snap:
  commands:
    - 'snap install --classic kubectl'
    - 'snap install --classic helm'
    - 'snap install jq'
    - 'snap install --classic certbot'
    - 'snap install --classic code'
users:
  - default
write_files:
  - path: /etc/skel/.xsession
    content: |
      xfce4-session
    permissions: '0640'
  - path: /etc/skel/.bash_profile
    content: |
      if [ -f ~/.bashrc ]; then
          source ~/.bashrc
      fi

      export PATH=$PATH:/usr/local/go/bin
      alias docker=podman
      alias k=kubectl
    permissions: '0640'
runcmd:
 
  
  # Install Podman
  - source /etc/os-release; sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  - wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_20.04/Release.key -O- | apt-key add -
  - apt-get update -qq -y
  - apt-get -qq --yes install podman
  
  # Install dotnet core 5 - https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-
  - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - rm packages-microsoft-prod.deb
  - apt-get update
  - apt-get install -y dotnet-sdk-5.0
  
  # # change default RDP port
  # - "sed -i 's/port=3389/port=2023/' /etc/xrdp/xrdp.ini"
  # - 'systemctl enable xrdp'
  # - 'systemctl restart xrdp'
  
  # Install Azure CLI
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null; AZ_REPO=$(lsb_release -cs); echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
  - apt-get update
  - apt-get install azure-cli
  # - curl -L https://aka.ms/InstallAzureCli | bash
  
  # Install Terraform
  - cd /usr/local/bin; wget -o terraform.zip https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip; unzip terraform.zip && rm terraform.zip
  - cd /tmp; wget https://golang.org/dl/go1.17.1.linux-amd64.tar.gz; tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz