#cloud-config
package_upgrade: true
packages:
  - xfce4
  - xfce4-session
  - xrdp
  - python3-pip
  - flameshot 
  - i3-wm 
  - rofi 
  - i3status 
  - suckless-tools 
  - apt-transport-https
  - firefox
  - gnupg2
  - unzip
  - ca-certificates
  - curl 
  - apt-transport-https 
  - lsb-release
  - gnupg
snap:
  commands:
    - 'snap install --classic kubectl'
    - 'snap install --classic helm'
    - 'snap install jq'
    - 'snap install --classic certbot'
    - 'snap install --classic code'
users:
  - default
write_files:
  - path: /etc/skel/.xsession
    content: |
      xfce4-session
    permissions: '0640'
  - path: /etc/skel/.bash_profile
    content: |
      if [ -f ~/.bashrc ]; then
          source ~/.bashrc
      fi

      export PATH=$PATH:/usr/local/go/bin
      alias k=kubectl
    permissions: '0640'
runcmd:
  # Install Docker
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

  # Install Azure CLI
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null; AZ_REPO=$(lsb_release -cs); echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
  - apt-get update
  - apt-get install azure-cli
  # - curl -L https://aka.ms/InstallAzureCli | bash
  
  # Install Terraform
  - cd /usr/local/bin; wget -o terraform.zip https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip; unzip terraform.zip && rm terraform.zip
  - cd /tmp; wget https://golang.org/dl/go1.17.1.linux-amd64.tar.gz; tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz