#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - gnupg2
  - unzip
  - ca-certificates
  - curl 
  - apt-transport-https 
  - lsb-release
  - gnupg
groups:
  - stepca
users:
  - default
  - name: stepca
    gecos: step-ca server
    primary_group: stepca
    ssh_authorized_keys:
      - ${ssh_key}
write_files:
  - path: /tmp/stepca/config/ca.json
    encoding: b64
    content: ${step_config}
    permissions: '0640'
runcmd:
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
  - AZ_REPO=$(lsb_release -cs); echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - sudo apt-get update
  - sudo apt-get install -y azure-cli
  - wget https://dl.step.sm/gh-release/cli/docs-ca-install/v0.17.6/step-cli_0.17.6_amd64.deb
  - sudo dpkg -i step-cli_0.17.6_amd64.deb
  - wget https://dl.step.sm/gh-release/certificates/docs-ca-install/v0.17.6/step-ca_0.17.6_amd64.deb
  - sudo dpkg -i step-ca_0.17.6_amd64.deb
  - mkdir -p /opt/stepca/config
  - mkdir -p /opt/stepca/certs
  - mv /tmp/stepca/config/ca.json /opt/stepca/config/ca.json
  - chmod 0640 /opt/stepca/config/ca.json
  - chown -R stepca:stepca /opt/stepca
  - echo "-----BEGIN CERTIFICATE-----" >> /tmp/root_ca.crt
  - cat /tmp/root_ca.txt | sed -e "s/.\{76\}/&\n/g" >> /tmp/root_ca.crt
  - echo "-----END CERTIFICATE-----" >> /tmp/root_ca.crt
  - mv /tmp/root_ca.crt /opt/stepca/certs/root_ca.crt
  - rm /tmp/root_ca.txt; rm /tmp/stepca